import { Inter } from "next/font/google";
import "./globals.css";
import Sidebar from "@/components/main comp/Sidebar";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "FIXIROR",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <main>
          <div>
            <Sidebar/>
          </div>
          <div>
            {children}
          </div>
        </main>
      </body>
    </html>
  );
}
